
platform :ios, '8.0'

use_frameworks!

target 'AWSPods_Example' do
  pod 'AWSPods', :path => '../'

  target 'AWSPods_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
